from scipy.cluster.hierarchy import linkage, dendrogram
from scipy.spatial.distance import pdist, squareform
from scipy.misc import toimage
import numpy as np
from glymur import Jp2k
import StringIO

def hide_this(xxx):
    qstrings = '''FGIJJJKFLLGLGPKMFMMILMHMMKIKIKMJKLLKLMHIIDKNHLIKKOLJLNELNLLFKKKKIM8FKLNJJ?KLJIKIKLEILKNJDILJIHDECAA@
    FEIFGKFFLLLJGDKKFGHCINNHHIHEJKMHKDLKLH;JLHGMHMJJLKIJLKFLJLCHKKKIIMJGLFNJJIKJJJA?G6HJEMAJK1IB?FGECBA5
    BEIGHGKLHHMLGFKMHGKNINNMMHKMJK=JGMIHLHMHKJKILLLINKLJKGELKLKHGKKIBE8GJFJJLLKMJLKJHLE7>KIJK>HG6BDACA3C
    EEIBJKKLJLDJILKMKMJKMMNMJMJEJIMHHGJLLKMJLKKLLHNKLOJJBKFLILKMJMKILMJ,KMNLJLKJMIMJKMJHI@LEKM>JFGGDC?AC
    F?F6AGCBBBDJBGKM/AHGIGCDMF?@I/=BG;EDHH;CGN=ILHL:LAL;KGFA:LG@-KI7IDJ7K8@F7I7987KJ6GKIMJIJKIIE??,D>+>&
    B?IJILCFLGGJJKKMKMMJHKNDMMJKMLIKNGLIHH4ILNKJLMNKLILJ?KKCKLMMKJKIIMJJKKLJ7L7JJJJJDLJJEJNJKM>5,E@AC?A=
    FEEBILELJHJJLPCMHIJMHFNMM<EIIIIKKLJHLMMGIKKMLMII:KJJKKK9NLKFH,IIIK8FKMM7JIFLEI6JGIE7'FI76JLBIHD6AA>=
    BEGGJKKFLLKFKDKMIGKNANHMHMEIIIMMKLLHHHMHIJKJHHJLLOIJKKL-NLI8:MLJMD8ALKJJ7GKMJIJJJLKJEKIJKMIJJGGACAAA
    F9@=5C:JBBLL7:+C:AA:4AN32<2E.<F==.>=L/;:DKKM:L;BLACHDK:--FKFCF'7B7J,6L77J?7C87676G5'5@IJ%>6G?F6,A?3=
    AEDBJIKFLKJGGKKG;MKNIMHMMHKMMGIMHHLK=KMLHHLJLENHD:HEMGLGALCMK8LJBEBJKKMIJ?CIEJ6J@>>LJJIJKDHGBEGDA5?=
    EGIJIIKLLLJJJMIMKMKIIHHFEMIIM<MMKJGHGMMJLNKLLEKILKCDMLKLHLKMKG7KHKHHKKLFJJKGHJ@JJI>LMK7J6GHEIBGDC<A:
    FGDJJKKIKGLKGJKMIMKEHKNMMHJKILFKHMKHLKMNLDKLLHNHKOLHLKKLILMKKKKIBMJHKLNJLICMJJJJNMHHIJLEKI6>IHEDCBA5
    EEI=JCCBLKLGJ5KC2AJJFHCDHHKIMCFFKDLH=HFCIKKE:H;I:D:H9:LCAA;>9J,KJ7HJGKEL7JEM8J@J@,HI5FN7KD%7IB,6,??(
    HGILJKKJJLKLGKKMKGKMMINMMMKMMLMKKGLLLHMIHKLILMNJLOLJKKKLNLCGJJLKJMJ,KL7@LLKLAGIJK>JJD7IJK5HJ,,=AA<?@
    FGGFJIKLLKGLIJKHEGKGL4N?JMJGJKMHNM>KLHMHDKKLFHGBDA:JK:KGHFLK-BLKJDJ,JK'JDGKME,JJ6G+IDJ7JFDIJ6,DA<<A:
    EEIGJKCLFLJGJJKMIIAEHHCHJMJIILMKGJLIHKEIHJGLFHLLKKLJLKKLHLGH:MHKIEG'KLJILLFJA>>B@MK7JFF7=16+IFG,<?3A
    F.IKJKGLHKLAOMKMEDKCIHNMMMHMJLMBKDLHFKHGHKKIJHJKNGICLNKLILKMLKOKMJJJKFILL?KMJIJJKMJ7DFIJKIEJJ,GECB3(
    BCIFJCKBLLGFBGKCEGNJMANFEME@IMHHKMCIHHHJIJFEAMCHKGLJMGLIK9;JHGHFIMILKMIJJGKMMJKJJLJJJMICCG>I66CDCA>-
    HEIJJGKJLMJJIMCMFMHMIKNMMMIKMNMMMJGKLKMNLKKMLLKJLKLJLKML:LIMKJOILMJMKKLJHK@MJIIJNMHJMFLEEMIGIHDD6?A=
    BEIBHKKIILKKJMKMKIDIMIJMHM?IJNIKGLLILKMFLNKGLHNBLOIJLKKLNLIMKKIFJMJLFKJLLLFCJ@KJKLJJIKLJDMHJJG=DCB;:
    A?@BACCIFKDEGDCEFGAEIKCM?I?KDIMBGJJIFHFFHNKIC;CKN.J;B:FADFGBKF7AJAH,?L,7J7E-A7IIH>5HIFAJFD,>'B,6<5A(
    BGIJIKKIBHKEBFIJKGKCLKNMJH?KMIMJGMLIFHMGI;KLF;KKLGJDMKLKGLLGKKKKHJJFKMNJFDKGMJKDNI>JJKNJKMHGF?DD<AA=
    FEFKJIKLJLKGIMKHKIAIHKCM?MKKE<MMGJIKLD<HIHKIFMJKJKLJLLEL:LLH:FIAMMHGKK7JFIKJJJEINIKAIK7EDM>GI6DAA<A(
    =CIFILCJLLKLBJKMKJHJLHNMEMKEMLMMMDLLLKMIHHFELHKHMOIJLKLLNLKHLMHA9KJG>0J7HGCGM@IBJGKIIMNA+@HGI?,DC+A@
    FGIJJKKLJKLJLJKMCMJMMMNMJMHIIMMMNHLKLMMNHKKOLMGLJOLJLLLGHLCHKMIIHMJJJKIL7DKMJJJJHLHJJJOJDDH5FGDACA;=
    >#IJJLKIJLJGIKKMHMDKHHGMMMIIJNIMMMLKHHMJIKLLLMNLJKJJLKMLKLK@6KLKHMJLKJJLHLKGM@E7KL>IJMLJD5A3?FE=CA?=
    HEIKJKKJKLJJJGKMIMJKMMNMMMLKJLMJMMLKLMMIIKNNLMJJNKLJKLLLNLKMJMIILMIJLLLJJKKIJLKJKMJAMJIJKIHHJEGDCB>>
    FE@KJGGILLKLJFEM:GKKMNNMMM?MILFHMJLDLHIHHJKOLJJJLILJLKEGJLKJKKIKJMJKGKLLJLKJJJJJNMJLJKIJKMEGBGGEC?;>
    <CGFJJKLKLKJFJFMFMKN4KC3?H?@I/HBGC>HFMF:LKG<JLL:LE7AFABIKLK@HGLIRMHAJEEJ7I7GJJK?,>>ED@7,EDEGF6C6@B=0
    CEIKJKKLLKJKJMKJHMHMMKNMEMJGMMKMNHGKLMHJLKNMLHLKLOLJKKMLNLLMLJKIREJKLMLLLLKNJIMIGMKEMKL7KMIGJBDECB>(
    EEGJHKKILLDJODKMHAJELKNMHMH@MIMHMGCIGMIILNGILMJLL<:JMKKLNLGKKKHFJKJGJLNJLLKIJIJJDLKHJJIJKDLJFBGEC<>0
    FGIKJLKLJKKLLMKMHMMJFMNMMMJIJLIMNMILLMHJKNKJLMNJKOLJLKMLNLLMKMKFIMJHKMMJJJKJMLMJNMEEIJLJKAHHIEDEC<AC
    ;EDFJKKJKMJKILEMKMKMIMNMMMKMJLMMK(GHGHAHIJDI:EIBJ:H;D-LIHF.,(B7'9'8A>#%J7,,JH7,7,,E,D'',#/6+''@D6+A-
    FCEKJGKLHHLJJDKMHJKHLMNFMH2GII=BKMCHLDMGIH=IHHGIND:JMGLGJLLM:KKAB,JJ6EJIJKEIJGEJGCJEIKNJD5E+IHDAC5>5
    FEI=JIFLFKKJODIMIMMILMDMHKLIJMMMKGIKFHMJIHK<LEIKLKLJ?GKLILKMKFIFMKJL?LMJII7JHGKJK,HEDKLE=MBII?DE<B?-
    CGFJJKKBLKIGFPKMKMKCLNC?MMJIJMMKKLLKGHGJHNKOJHC:NKLJFKMLILKHKJIFJMEHLMILF?BIJJKJNLJLJKIEKILJBGEECBA(
    <C@GJKKLJLDJOMKMCMDKLHCMMIEKMIMJNMELHHEGLJFMLLIJFILFLGKEJFKHJ8HKLKJKFKELJKKIJJJJ@GJ7LKLJ@IIHIB@ECBA-
    EGIGJIKLJLILGLEMKMGKIKNMMMJKMLHHK;>LLHELLJKLLHGLLKLJLKLLKFKMKKIKHKJLGJNLLJKLMLKJKLKHEMNJFGHBFFGDCBA>
    FGIJJKKJHLKJJJKMKGGMIKNMMMJIMNIMKJLKEKMJHKKOLLJKLOIJLKKLILLMKBKFLMHLKKNIJLKLJGKINMKEI@NJDJLHFGGDCBA-
    EGIFJLKILKDLGJKMHMNJIMNFMMJKMMMJLLLLLMMGINNGLLJLJOJJLKMLNLLKJKOORMJLLMEJLJKCJJJJNMHHJJFEKM>BIGDAAAA@'''

    qstrings = '''!111177777@@@@@@@@@C@@@C@@@CC@@@;@@C@@CC@C@C@@C@C@####!!!!!!!!!!##!###!!!#!!!!!!!!!!!!!!#####!###!!!!
    !#################################!!#!###############!!!!!!!!!!!!#!###!!!#!!!!!!!!!!!!!!####!!###!!!!
    !#################################!!#!#!####!########!!!!!!!!!!!!#!###!!!#!!!!!!!!!!!!!!####!!###!!!!
    IIIGIGIIIHIDIIIDIIIGHIIHIIG@GIIHIFIDIGIIDGEGEGIIIDIFIDI=<?!!!!!############!!!!!!!!!!!!##########!!!!
    !######################################################!!!!!!!!!###########!!!!!!!!!!!!!#########!!!!
    !,2+*24525@@@@@@@@@@@@@@@@?@?@@@@@@@@@@@@@@@@@@@@@#####!!!!!!!!!###########!!!!!!!!!!!!!#########!!!!
    !--++22355@@C@@C@@@@@@@@@@@@@@@@@@@@@@C@@@@@@@@@@@#####!!!!!!!!!##########!!!!!!!!!!!!!!#########!!!!
    !121-88888C@@C@@@@C@@C@CC@@@@@@@@@@<<<::@@@@@@@@@######!!!!!!!!!###########!!!!!!!!!!!!!#########!!!!
    IIIIIHIIIIIGHIIHDIIIGG8GGIGIGIIGGIHHI<HGIDIEEEI@BDE>FEEE<DDG@@EECAACC<8>=A?###!!!##!!!############!!#
    ##########################################################!#!!!#############!!!!!!!!!!!###########!!#
    ############################################################################!#!!!#!!!!!###########!!#
    HIIIIHIIIIIIIIIIIIHIIIIDIHHBHIIHIIIIBIIFIIIDHBDDDGDGGG@GGICGHFHEIIBIEHB-=A?#!#!!!#!!!!############!!#
    GGDGG@GGGEGGG@GGEGGGHHFHHHHHGHHFHHHBEEGGHHGHHBEBGGEBEEDEF<G@DEDE>>AAAC?#######!!!##!!!############!!#
    DDDB?=0B?=DBDDDDDD@DBB@>1B@BB?>B<>>D><DBD@D@@DDBDDCBBAB5BB####################!!!##!!!############!!#
    HHHHHEGEGGFGGGGHHGHHHHHHEGHHFHHHHFGHHHHBGDGBEEHHFHHGFGHGDGHEFEF3E####################################
    IIIIIIIIIIIIIIGIIIIIIHIIHIIHIDIIGIHIIIIIIHIH>CEEHHGDHBGGDBEDEB@8C=BB@ACBA@>B@BC@@BB>>?76?#########!!#
    HHHHHHHHHHHGHHHFGHHHHHHGDHHHHHBHHHFEDDFFHHGGGHHDG8EEEEEAE<EE@BBDB#################################!##
    #####################################################################################################
    IIIIGIHIIIIIIIIIIIIIIHIIIHIHDIGIIIGIGHIBBG@GGIGGIDGGHIHGIBEGEB@FEB<@DBD@A@D###!#####!#############!!#
    ?BDDD@D?DDBBD@B:?4BCDDD@DD>DBD################################################!#!###!!############!!#
    HHHHHHDHHHHHGHHGHHBHHGHHHHHHHHDDFGEHHHHHHHHHH>DBBDGGEGBFEBG@BDDGBHFHHEEG8G>E@C7A/1646<C##############
    IIIIIIIIIIIHHIIHIIIHIHHIHIIIIFHHIIIHHIGE>IHEFFHHHCFGHGCGGBGCCBC@CDD>EB>9:B@##########################
    GGGGGGGGGGGG>EEGGDG>E,CACD@DDGCC+>>=8=?ADDEBEA<>CA###################################################
    IFHIIIIHIIIIIIIIGIDDIIIHIIIIDD??+B###################################################################
    B:DD@D:DDDDDD<:D?B@@@B>B8?D<><.0'0/B>B>=DDDDB########################################################
    IHIIIHIFIIIHIIIIHIIGIIIFHBIIIGE?C2CADGGDIHHDHGFHFGHF@HEGEGGEDEHEGAA?7CBCBB@@B@B@=?A?A################
    :DGDG?EEE:BGGEGGEGGGDGG@EGG@G8EGBGGGDDGGGDG>>GGGEE<GG3DGG@DGD@GDBGDBB>D@A@BD8DD>D>B@#################
    @DFGFEDGGBEDEEBEEEDBEBEEEDEBDE=B9?AC9A;>;A>9=?>6A955-@###############################################
    GHIIIIIIIIIIIIIIIIHIIIHIHIIIIIIFIIIIIIHIHIIIGIGDFEDBFIGEF@DFGGHHFHHHFBBDDB@E<EEBBBBCEB@EAA:8>=0;7<50@
    GDGGGDEGDGEDDGDGGE@GEGGGDDCFEGGG>EEC8A;ACCA9ABB>@B@@BB9BBDD5=A;A0?2-36=:748;8@>>99@<@################
    HHHHHHGHHHHHHHHHHHHHHGHHHHHHHHHGHHHBHHGDHHHHHHHHHBHHHFHCHHFHDBDDDBDG<D@EFFEFECBC#####################
    #####################################################################################################
    EBBBEB>BBBGDG<<E?EB?8AAAA0<74;<8?2<:1;?##############################################################
    IIIIIIIIIIIIIIDGIIIIIIIHIIHIIHIHGIGHHIIIBIHHHHEHG8EEEHEBECEE@BEEDEAEEC>>CB=A?########################
    IIIIIIIIIIIIIIHIIIIIIIIIIHIIIIHIIIIIHHIHHIIHHBHHDEHHGGGF@DEH>FAA<A?AA?5<'8<@@BB=?=??3A=??>*-7;9?8:?7@
    IIIIIIIIIIIIIIHHIIIIIFIIIIIHIHIIIIIIIHHHIHIHGFEHFFDEIBDFEEEBDEBDGBB?CF@3@?@<>?;74=7=:@@>@@@@#########
    HIHIIIIIHIIIIIIIIHHIIGIGIIIIIHGIIHIGHIIHIDHDIHIHFGHFGGDEFEEF?CACC>?@?*=A<<<?#########################
    IIIIIIIIIIHIIIIIIIIIIIHHIIIIIIIIIIIIIIIIGIHHHHHIIICGGEEGHHHGGEHFHADC=B<BBBB?@?@B)<=7<??@??AA;@#######
    IIIIIIIIIIIIIHIHHIIHIIIIGHGIGD>EC####################################################################
    IIIIIIIIIIIIIIIIIIIIIIIIIIIIIGIIIIIHII@IIBFIHIEBAIDD@BDHEEEB8EECEEE0;C@B@@=@::A?0???;3@##############
    IIHIHIIIIIIIIIIIGIIIIIIIIIIIHHD>EEGGIIDBHIIHIIIFBFGFHFBEDF>,<3<;=;?2+A###############################
    HIIIIIIIIIIIIIIIHIIIIIIIIIIIHIIGGIIIIHIFIHHIFGEIDCIDDEFHEBFEGGIEHD@G8DAD@BDD@CEE<@DDBBD@BB?D<B>@@?,<?
    CBCBABEE@@GGEG8GGGGGGEGDGHHHHFGGEGGGHHDDHHBHDHFHHHHHBHDHEHDEHCHDEB<CEEHEFEHD<@FEDBD0B@D@=D07.7783?###
    #####################################################################################################
    IIIGIHIIIIIHIIIIGIIIIIIIHBIIHIIIHIIEHIHHHEIHFIIIIHGGHFHBIDEEGGEGEGDEGF@BB@>@;9=;;?1;?5?##############
    #####################################################################################################
    GG@GDGEGGE@@B8E>>9/;?::=8B??8?#######################################################################
    IIIIIIIIIIIIIIIGIIIIIIIIIIIIIHGIIIIIHHHIHHHHIGIIIGIFFIH<CEEBCFB@G>C??8DBBBB2@CA8<<;&=?8=A############
    GGGGGGGEGGGGGGGGGGGGE@###############################################################################
    IIIIHIIIIIIDIIIIIIIIIIIIHIIIHIGIIGHIIHDIIGIIHIIHEIHEHHEFCFFBADEBDFEBBBBBBD<+==?;BCB##################
    HHHHHHHHHHFHHDHHHHHHHHGGHHHGHHHHHGGGGGGBBBD),42454A?#################################################
    IIIIIIIIIIHIIIIIIGIIIIIIIIHIIHHIIIIHHIIIHHIHEIFDIIIHFDFEIEIEC:AEA?CA>CA?@E@?8?A?5;<2;=?AA############
    #####################################################################################################
    G>>DGGBGGGG>DGGHB8GEE8DGGBG3DBGGEGFE>DCEEFFFG2BD>EBFCCB=?3A>?7;=:>@,>@@1::?##########################
    DGEDHGG?<BBFBAFGBBEEBGEGG<GBEG2<9?7EB8CAB?<<B:BB6?###################################################
    IIGIHIIGIIFIIHIIIIIIIIIIIHIHIIIIGHHIHHEHCGHEEEEE@FBEF@@DBDCBED@EDBDBBC@2B@B@==A=<9')<=6;?=?##########
    HIIIIIIIFIIIIIIIIIIGHIIIIIIHEIIIHHHGGGHIGFIGHGHHDEFDDEEAEA;BCB>>BC@@?################################
    HHHHHGHHDHBGGGGGGGGGGBGDBF<GEEGFC<E?+=>:BD8@>EEE>F?>A<>AD85*8/28===C@################################
    IIIIIIIIGIIIIIIIEIIIHIIIIIIIGIIIIIEEIIIIIIFIHGIIIGIGEIBFFEDFDIBFHEC>DEEHHF@A3=8?=<4><@@8?:C6?@?######
    GGG@EGEGG>DGGGDHHHHHHHHHHGGGHH<EEGFE>DGGGHHBHDD-B####################################################
    #####################################################################################################
    IIIIIIIIIIIIIIIIIIIIIIHHIIIIIIIHIIDEB>F;AD<ABB3A;@?=?;=@@86?@@BC>BBB2B=1<7.;;00;?6=70??##############
    :DGDBEDGGGGGGGBGDGGBGGGGGGGBBGGGG?EGG<EG<8BB=0796:=4=B###############################################
    HHHHHHHHHHHHHHGHHHHFHHHHHHHHDHHHDEHB@GBGFFEFDHHHHHFHGHEC;D>FDA6@BB@B@BEBBD###########################
    #####################################################################################################
    IIIIHIIIIIIIIGIIIIIIIIGDFIIIIIBFIIIIIIIHIIIIEIGIIIHHIIHIIIHGBFIDG@BD>G<GCEEEGED8BBB<@>BDDD3??>?AC2>><
    DDDDDDDDDDDBD########################################################################################
    CCCCCCCCCCCCCCCBB@###################################################################################
    HHHHHHHHHFHHDHHBHHHGHHHHGHHHHHHGHHHHHEEBAC>3A>8A#####################################################
    GBEEEBDFFFHHHHHHHHHBGGGEBG@GGGEF@GEGBD<BG8DADD@D+DAEA8,A>=A=8A#######################################
    GEGGGG@G<GB=1BBGGG@GBGDGGBAEEA8?BB?08:==GFGBDEEBBD>AA8AA>CA>@BD@B2D@;;BB@BB?53?######################
    IHIIIIIIIIIIIIIIIIIIIIIIIIHIIIIIIIHIHIHIHIHHHHHGGGEGG>GGEEDGD@CDB####################################
    HHHHHHHHHHHHHEHEGEGDHHHHHHHHHHHCHCHBCEGEHHBHHE>FHHE@@CEBBBBBEBDHCB1DAA>CAA>B<@B>=3.:>9A=@############
    DHHHGHHDHHHGEHHHHHHHDHHHHHHHHHHGHHHHGGGEDHBGEHEF@HGBGGHHGEGDFBD=>GDDDBBEBD3GG<38ABEEB8<8ABGE<BD8<B88D
    IIIIIIIIIIIHIIIIIIIIHIIIIIIIIIHIIIEBHIHIIHIIIHIIGFGFFGIGGHIDGEGAGHBBB@EBEDDGGE<GBDB##################
    ;-<)===>3'/705<183;9,96=(?;2?===/592'42)@@@@@@@@@@###################################################
    HHFHHHHHHHHHHDHHBHHHHHHHHHHDHFBGGGDHGHHHHHHEHFEDEBDDDBB==<?=A?=?ABDB@D###############################
    HHHHDHGHBDGGBGGGDGGGHHHHFEDDGE<GDDDHEHHHFBDD>B8B@BDCEC@CBC###########################################
    IHIIIIIIIIIIIIIIIIHIHIIIIIIIHIGIHIIHIIIGFIIGGDIFEHHHHDF<BB8D=<?######################################'''

def qual_ord(phred_string, offset=33):
    return [ord(x)-offset for x in phred_string]

#quals = [qual_ord(qq)[1] for qq in qstrings.split('\n')]

def img_cluster(quals, hackish_counter=[0]):
    aa = np.array(quals)

    for linkage_method in ['average']:  # ['average', 'complete', 'median', 'single', 'ward', 'weighted', 'centroid']:
        D = squareform(pdist(aa, metric='euclidean'))
        Y = linkage(D, method=linkage_method)
        reorder = dendrogram(Y, no_plot=True)['leaves']

        img = aa[reorder]
        return img, reorder
        # #j = Jp2k('dummy.jp2', 'wb')
        # #j.write(img.astype(np.uint8))
        # im = toimage(img, cmin=0, cmax=255)
        # im.save('clustered_pngs/pil_dummy_%d.png' % hackish_counter[0])
        # hackish_counter[0] = hackish_counter[0]+1



#        im = toimage(img, cmin=0, cmax=255)
#        im.save('clustered_quals_%s.bmp' % linkage_method)

CHUNKS = 256
png_counter = 0

with open('gage_rhodo/frag_2.quals', 'r') as infile:
    quals = []
    png_buffer = []
    for i, line in enumerate(infile):
        quals.append(qual_ord(line.rstrip()))
        if (i % CHUNKS) == CHUNKS-1:
            image_array, order = img_cluster(quals)
            png_buffer.append((image_array, order))
            if len(png_buffer) == 10:
                print i+1
                to_png = toimage(np.vstack([x[0] for x in png_buffer]), cmin=0, cmax=255)
                to_png.save('clustered_pngs/shortjump/frag_2_%d.png' % png_counter)
                with open(('clustered_pngs/shortjump/frag_2_%d.txt' % png_counter), 'w') as order_out:
                    ordering = [x[1] for x in png_buffer]
                    for oo in ordering:
                        order_out.write(' '.join(map(str, oo)) + '\n')
                png_counter += 1
                png_buffer = []

            quals = []
            #print i+1




#import Image
#im = Image.fromarray(np.uint8(cm.gist_earth(myarray)*255)) # apply colormap directly, convert type